### ISSUE TITLE
프로젝트 환경설정

### ISSUE THREAD

**Issue by CheolhoJeon** [develop-playground/jeju-road-back-end#1]
작업 내용은 아래와 같습니다.

* `.gitignore`
* `README.adoc`
* 의존 추가
  * 스프링 부트
  * JPA
  * Kotlin Plugin
  * Ktlint
  * ...
*  `.editorconfig`

**Comment by ByeongSoon** [comment]
기존 Kotlin DSL로 이루어진 gradle 파일에 에러가 발생하여 프로젝트 환경설정 다시하겠습니다.
 - .gitignore, README.adoc은 유지하고 프로젝트 빌드 시 spring initializr 사용
