### ISSUE TITLE
`README` 파일 컨트리뷰터 작성

### ISSUE THREAD

**Issue by CheolhoJeon** [develop-playground/jeju-road-back-end#32]
현재 `README` 파일에 컨트리뷰터가 저만 작성되어 있으므로, 팀원 모두의 정보를 기재합니다.

**Comment by CheolhoJeon** [comment]
각자 본인의 영문이름과 이메일을 댓글로 남겨주세요.
해당 이슈 담당자가 취합해서 작업하면 될거 같네요.

**Comment by ByeongSoon** [comment]
댓글 남겨주세요~~ 제가 수정하겠습니다.

**Comment by MoochiPark** [comment]
Daewon Park
moochi@kakao.com
입니당~

**Comment by isoono** [comment]
Soonho Hwang 
tnsgh211@gmail.com 
입니다~!
